project_id = "aobacfnkcurqmffsqaqj"

[auth]
enabled = true
site_url = "http://localhost:3000"

[functions.create-payment]
verify_jwt = true

[functions.sync-stripe-products]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false