// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aobacfnkcurqmffsqaqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvYmFjZm5rY3VycW1mZnNxYXFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NDE2NDAsImV4cCI6MjA2OTUxNzY0MH0.L399bfAgGQezhIjI7SR2P1WikAlQoJgT8UJo8lMvcmM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});